apiVersion : apps/v1
kind: Deployment
metadata:
  name: prahaskappointmentservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prahaskappointmentservice
  template:
    metadata:
      labels:
        app: prahaskappointmentservice 
    spec:
      containers:
        - name: prahaskappointmentservice 
          image: email14.azurecr.io/prahaskappointmentservice
          ports:
          - containerPort: 8091